# Copyright 2026 Terradue
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: "3"

vars:
  PUML_VERSION: '1.2026.8'
  VSIX: cwl-uml-viewer.vsix

tasks:
  update_plantml:
    cmds:
    - mkdir -p vendor
    - |
      curl --fail --location \
      https://github.com/plantuml/plantuml/releases/download/v{{.PUML_VERSION}}/plantuml-asl-{{.PUML_VERSION}}.jar \
      --output vendor/plantuml-asl-{{.PUML_VERSION}}.jar

  update_python_modules:
    cmds:
    - |
      pip install \
      --only-binary=:all: \
      --target vendor/python \
      -r python/requirements.txt

  default:
    desc: Package and install the extension in the local VS Code instance
    cmds:
    - task: install

  package:
    desc: Validate the extension and produce its VSIX package
    cmds:
    - npm run package -- --out "{{.VSIX}}"

  install:
    desc: Package and install the extension for local debugging
    deps:
      - package
    cmds:
    - code --install-extension "{{.VSIX}}" --force
